### ISSUE TITLE
Do you really need isomorphic-fetch in here?

### ISSUE THREAD

**Issue by fzembow** [jonbern/fetch-retry#22]
Useful tool!

But we don't need isomorphic-fetch, since we already polyfill with another approach and do not need node support... isomorphic-fetch adds unnecessary bloat to the bundled javascrit.

Do you feel strongly about having it as a dependency here? Feels like users could provide their own polyfill in a wrapper if needed.

**Comment by jonbern** [comment]
You raise a valid point, especially for client-side usage of the library.

I have looked into a couple of different approaches, but I have not found a satisfactory solution that will not change the approach/philosophy of the library (to be a platform agnostic drop-in replacement for `fetch` that adds retry functionality).

I will have to study the main JavaScript bundlers more in detail to see what opportunities they give us, but as I want to continue to support `node.js`, and since `fetch` is not a native API in `node.js`, I don't think we will get away from at least defining a `fetch` library as a dependency. Right now I think the best possible outcome is that it will be possible to utilise tree-shaking to remove the underlaying `fetch` dependency at build time, if another polyfill or browser implementation exists.

If you can think of a viable approach that will preserve the library philosophy, I'd be more than happy to hear about it and consider it.

Another alternative is to fork the library and build a browser specific version of the library. But even with that approach, it would change the library in many ways, since you don't need a drop in replacement if you already have a native implementation or a polyfill. Instead, you would want to extend the existing implementation.

**Comment by Otto-AA** [comment]
Have you thought about passing the fetch method as parameter? For instance like this:
```javascript
const FetchRetry = require('fetch-retry')
const isomorphicFetch = require('isomorphic-fetch')
const fetch = new FetchRetry(isomorphicFetch)
```

The disadvantage would be, that those who want to use isomorphicFetch would need 2 additional lines of code and 1 additional `npm install isomorphic-fetch`. To me this seems reasonable compared to the benefits of being able to choose which fetch to use (e.g. window.fetch or a maintained version of isomorphic-fetch like cross-fetch).

If you slightly want to reduce the amount of work for the user you could also install isomorphic-fetch yourself and provide it like this:
```javascript
const FetchRetry = require('fetch-retry')
const isomorphicFetch = require('fetch-retry/isomorphic-fetch')
const fetch = new FetchRetry(isomorphicFetch)
```
Then no additional installation would be necessary and it shouldn't bloat the bundle if it isn't used.
