### ISSUE TITLE
Consider transpiling to ES5?

### ISSUE THREAD

**Issue by josh08h** [jonbern/fetch-retry#42]
Would you consider accepting a PR which transpiles this code into ES5 compatible Javascript as part of the build process?

**Comment by ptolemybarnes** [comment]
Or just merge this: https://github.com/jonbern/fetch-retry/pull/43 :-p

**Comment by jonbern** [comment]
I have merged @ptolemybarnes PR now and published a new version to npm.

Apologies for the delay.

**Comment by ptolemybarnes** [comment]
Hey @jonbern do you plan to maintain ES5 compatibility? If so please consider changing the eslint config here: https://github.com/jonbern/fetch-retry/blob/cf81581d9c41d85a6f6fddb567ffce13aabe40f3/.eslintrc.yml#L4 Otherwise someone will accidentally break it.

In the long term it might be worth transpiling to ES5 as part of the build step. Or just rule that the consumer is responsible for transpilation - I know a lot of projects do that.

**Comment by jonbern** [comment]
Thanks for the suggestion. The plan is to maintain ES5 compatibility so the `eslintrc.yml` file should have reflected this.

I have updated this now in #45 , where I have also made linting part of the test script in order to ensure that ES6 syntax and newer will result in a broken build.

For now I would like to keep it simple and not introduce any transpiling. If the current solution is not sufficient I will consider transpiling in the future.
