### ISSUE TITLE
How to refresh access token before the next retry

### ISSUE THREAD

**Issue by nwaughachukwuma** [jonbern/fetch-retry#53]
Please how do I refresh the user's access token in the case of a `401` and use it in the next retry?

**Comment by VasylBoyko** [comment]
I do it in this way: 
```
    const createHeaders = (token, attempt = 0) => ({
        Authorization: `Bearer ${token}`,
        'x-attempt': attempt 
    });

    const headers = createHeaders(localStorage.getItem('access_token'));

    fetch(fetchUrl, {
        headers,
        retries: 3,
        retryDelay: 1000,
        retryOn: async function (attempt, error, response) {
            headers['x-attempt'] = attempt + 1;
            if (attempt >= 3) return false;
            if (error !== null || response.status === 401) {
                const updatedTocken = await refreshTokens();
                headers.Authorization = updatedTocken.Authorization;
                console.log(`retrying, attempt number ${attempt + 1}`);
            }  else if (error !== null || response.status >= 400) {
                console.log(`retrying, attempt number ${attempt + 1}`);
                return true;
            }
      }
    });
```

**Comment by ptolemybarnes** [comment]
@nwaughachukwuma I guess modifying the request between retries is not really supported (except via mutate-y means as @VasylBoyko suggested). @jonbern Is this something you would consider supporting? maybe the `retryOn` function could return an object that gets merged into the headers.

**Comment by VasylBoyko** [comment]
> maybe the retryOn function could return an object that gets merged into the headers.
That makes sense, but why headers only? F.e. use case: on 502 set delay to 10s  and retry until the server isn't up,
in case of 404 -  reject the request promise.
To do this we need to update the whole object with fetch options, not only headers.
Also, we may need to update the fetchUrl:  
http://host.com/endpoint, 
http://host.com/endpoint?attempt=1, 
http://host.com/endpoint?attempt=2, 
http://mirror_host.com/endpoint?attempt=3

so probably we need to update retryOn to something like:

```
const retryOn = (attempt, error, response, initialArgs) => {
    const [fetchUrl, options={}] = initialArgs;
    const updatedUrl = attempt < 3 ? `${fetchUrl}?attempt={attempt}` : `${mirrorUrl}?attempt={attempt}`;
    updatedOptions = {
       headers: {...options.headers, Autorization: `Baerer ${newToken}`},
       retryDelay: 10000
    }
   return [updatedUrl, {...options, ...updatedOptions}];
}
```

**Comment by ptolemybarnes1649** [comment]
@VasylBoyko yeah, I see your point. I'm wondering though, at what point can you no longer call what you're doing "retrying", but something else? Like chaining requests with different branching conditions. Maybe the scenario is outside the scope of this package.

**Comment by ptolemybarnes** [comment]
@VasylBoyko yeah, I see your point. I'm wondering though, at what point can you no longer call what you're doing "retrying", but something else? Like chaining requests with different branching conditions. Maybe the scenario is outside the scope of this package.

**Comment by jonbern** [comment]
I think this is probably beyond the scope of `fetch-retry`.

How about creating a local module where you wrap `fetch-retry`, and check the token expiration timestamp before invoking `fetch-retry`? 

If the token has expired, you can automatically refresh the token and provide the updated token in the request. Your local module could have the responsibility of setting the `Authorization` header for you, so that once you have authenticated you can make HTTP requests without having to explicitly set the `Authorization` header, and have token refreshes handled "automatically".

**Comment by nwaughachukwuma** [comment]
> I think this is probably beyond the scope of `fetch-retry`.
> 
> How about creating a local module where you wrap `fetch-retry`, and check the token expiration timestamp before invoking `fetch-retry`?
> 
> If the token has expired, you can automatically refresh the token and provide the updated token in the request. Your local module could have the responsibility of setting the `Authorization` header for you, so that once you have authenticated you can make HTTP requests without having to explicitly set the `Authorization` header, and have token refreshes handled "automatically".

>> I guess modifying the request between retries is not really supported (except via mutate-y means as @VasylBoyko suggested). @jonbern Is this something you would consider supporting? maybe the retryOn function could return an object that gets merged into the headers.

@jonbern it will suffice if `fetch-retry` allows merging request headers, as suggested by @ptolemybarnes

**Comment by imvinaypatil** [comment]
Can we allow returning the input object as suggested by @VasylBoyko ? Because we can apply custom rules based on the url or any other parameters. One use case I can think of is, we can whitelist or blacklist URLs from retrying when instantiating fetch-retry.

**Comment by jonbern** [comment]
I don't think it's a good idea, because it's no longer just extending the _standard_ fetch API with some basic retry functionality.

These kinds of business requirements/problems should not be handled in the HTTP client library, but be implemented in service classes or similar. If you need more complex retry functionality than retrying requests due to network errors, or checking specific HTTP status codes, then you probably have a bigger problem and should fix that at the root.

Why not just revert the standard fetch library for the urls where you don't want to retry HTTP requests?
