### ISSUE TITLE
Set up Fetch-retry

### ISSUE THREAD

**Issue by WInzelrac** [jonbern/fetch-retry#76]
Hi, I've tried to use fetch-retry but I don't get it. 
I've read the doc, I change my code but how am I supposed to link the API to my code ? 
I'm not a pro, it might be a stupid question, but it could be good to add it to the README.

Thanks !

**Comment by derSascha** [comment]
Depends on what you like to archive. You can use fetch-retry like the usual fetch. What example from the README does not work?

**Comment by jonbern** [comment]
Hello,

Not sure if I understand your question and if the problem is related to `fetch-retry` or is a general issue. 

`fetch-retry` needs to be imported first, and this is a lot easier if you use a JS bundler. Otherwise you can try out the suggestions mentioned here: https://github.com/jonbern/fetch-retry/issues/75. Once it's imported, it should be possible to use `fetch-retry` the same you would use the standard `fetch` API.
