### ISSUE TITLE
Access current URL in custom retryOn

### ISSUE THREAD

**Issue by derSascha** [jonbern/fetch-retry#77]
Thanks for the great fetch-retry!

Is there a way to access the current URL in custom `retryOn`? Right now, I'm using `response.url` but this does not work on exceptions. Any suggestions?

**Comment by derSascha** [comment]
Maybe some more context why this is useful. Using fetch-retry in the browser works only by replacing the global window fetch, as many frameworks don't support a way to specify the fetch they should use. This means all fetch calls now using fetch-retry and third party libraries might fail for various reasons, like tracking blockers or on mobile devices network errors. It would be very useful to distinguish between these problems using the URL.

**Comment by jonbern** [comment]
Thanks for your feedback 👍 

Beyond using `response.url` I can't think of any ways to access the url, except perhaps by creating your own `fetch-retry` wrapper that adds your own custom logic. I think this would add a lot of complexity, and I'm not sure if it is feasible.

Instead of using the global fetch instance, would it be possible to use a fetch polyfill and wrap that with `fetch-retry`? The second code example in the link below shows how to import the polyfill at the same time as you keep the original window fetch implementation.

https://github.com/github/fetch#importing

**Comment by derSascha** [comment]
Thanks for your response.

Providing `_input` to the `retryOn` via the `error` should already do it. My workaround looks like this:
```js
const originalFetch = window.fetch;
const interceptor = async (resource, options) => new Promise((resolve, reject) => {
  originalFetch(resource, options)
    .then(resolve)
    .catch((error) => {
      try {
        error.url = resource;
      } catch (otherError) {
        // ignore
      }
      reject(error);
    });
});
window.fetch = require('fetch-retry')(interceptor, {
  retryOn: ...
```
Now the response and the error object contains the url/request object.

**Comment by derSascha** [comment]
> Instead of using the global fetch instance, would it be possible to use a fetch polyfill and wrap that with fetch-retry?

To my understanding, this provides fetch to old browsers that don't support fetch, but how should this help to avoid the global fetch?

**Comment by jonbern** [comment]
My thinking was that you could use the fetch polyfill in your application code by explicitly importing it, and wrapping it with fetch-retry, and then reserve the global fetch to the third party libraries so that they would not be affected.
