### ISSUE TITLE
Question about 'retryOn'?

### ISSUE THREAD

**Issue by mattcasey** [jonbern/fetch-retry#85]
I want to add retries to our fetch lib and this wrapper looks perfect. However, I am wondering if there is an issue w/the default settings. If you don't pass in `retryOn` yourself, internally it is set to an empty array:
https://github.com/jonbern/fetch-retry/blob/master/index.js#L28
and therefore the result always resolves on this line:
https://github.com/jonbern/fetch-retry/blob/master/index.js#L73.
Is that intentional? It seems like the original code was expecting the default value of `retryOn` to be undefined.

This line, including the one where the default of empty array is set, are 3 years old so I think I must be missing something. Otherwise, why is `retryOn` not a required input, since the rest of the retry settings will never be used?

**Comment by jonbern** [comment]
`retryOn` is not required and is only used if you want to retry on specific HTTP codes. However, there can be network issues which causes the request to fail, and if you have not defined any HTTP codes that will be retried on, the library will still retry on requests that fail because of network issues. This is handled in the catch handler: https://github.com/jonbern/fetch-retry/blob/f375c7040211265b9c2939efc39438386d7844d2/index.js#L97

**Comment by RichardWright** [comment]
To revive this, what happens to network failures when the array for http codes is populated? Does it retry on those as well?

**Comment by jonbern** [comment]
Yes, it should retry on network errors no matter which set of HTTP status codes it is configured to retry on. This will trigger an exception and is handled by the `catch` handler of the promise in the implementation in `fetch-retry`.
